name: furia_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.1  
  firebase_auth: ^4.19.1 
  cloud_firestore: ^4.15.1  
  go_router: ^12.0.0
  firebase_storage: ^11.7.7
  flutterfire_cli: ^1.2.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.7
  http: ^1.1.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  image_picker: ^1.1.2
  google_sign_in: ^6.3.0
  mask_text_input_formatter: ^2.9.0
  percent_indicator: ^4.2.2
  flutter_multi_formatter: ^2.13.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - secret.env
    - assets/images/logo-furia.svg
    # - assets/icons/
    - assets/images/logo-furia.png
    - assets/images/logo-google.png
    - assets/teams_logos/
    
